// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_Ebl6PXYdLkLy2eITzMz8n4IYKEvNgc',
    appId: '1:334046732760:web:dc61c0f671ecf9c83c52ad',
    messagingSenderId: '334046732760',
    projectId: 'duwa-5e1a6',
    authDomain: 'duwa-5e1a6.firebaseapp.com',
    storageBucket: 'duwa-5e1a6.firebasestorage.app',
    measurementId: 'G-30LCFV932J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Mj8XKffWG-j9i7Rk5PzcZdDKiHfCMhw',
    appId: '1:334046732760:android:35e16b547c196f853c52ad',
    messagingSenderId: '334046732760',
    projectId: 'duwa-5e1a6',
    storageBucket: 'duwa-5e1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-GKSVFOVi93RyvWUVJS4N26DuA3ATGo',
    appId: '1:334046732760:ios:fc7aaae89116e2cf3c52ad',
    messagingSenderId: '334046732760',
    projectId: 'duwa-5e1a6',
    storageBucket: 'duwa-5e1a6.firebasestorage.app',
    iosClientId: '334046732760-m6tt1leg4p8gth2vc3ljdecf84g3koi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX-GKSVFOVi93RyvWUVJS4N26DuA3ATGo',
    appId: '1:334046732760:ios:fc7aaae89116e2cf3c52ad',
    messagingSenderId: '334046732760',
    projectId: 'duwa-5e1a6',
    storageBucket: 'duwa-5e1a6.firebasestorage.app',
    iosClientId: '334046732760-m6tt1leg4p8gth2vc3ljdecf84g3koi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM_Ebl6PXYdLkLy2eITzMz8n4IYKEvNgc',
    appId: '1:334046732760:web:b4aa0f01164046393c52ad',
    messagingSenderId: '334046732760',
    projectId: 'duwa-5e1a6',
    authDomain: 'duwa-5e1a6.firebaseapp.com',
    storageBucket: 'duwa-5e1a6.firebasestorage.app',
    measurementId: 'G-QJW19Y7LTJ',
  );
}
